export const ACCOUNT_MODAL = 'ACCOUNT_MODAL';
export const CONFIRMATION_MODAL = 'CONFIRMATION_MODAL';
export const CATEGORY_MODAL = 'CATEGORY_MODAL';
export const LOGIN_SETTINGS_MODAL = 'LOGIN_SETTINGS_MODAL';
export const PASSWORD_SETTINGS_MODAL = 'PASSWORD_SETTINGS_MODAL';
export const ACCOUNT_MEMBER_MODAL = 'ACCOUNT_MEMBER_MODAL';