const accountMembersTypes = {
  GET_ACCOUNT_MEMBERS_REQUEST: 'GET_ACCOUNT_MEMBERS_REQUEST',
  GET_ACCOUNT_MEMBERS_SUCCESS: 'GET_ACCOUNT_MEMBERS_SUCCESS',
  GET_ACCOUNT_MEMBERS_FAILURE: 'GET_ACCOUNT_MEMBERS_FAILURE',
  CREATE_ACCOUNT_MEMBER_REQUEST: 'CREATE_ACCOUNT_MEMBER_REQUEST',
  CREATE_ACCOUNT_MEMBER_SUCCESS: 'CREATE_ACCOUNT_MEMBER_SUCCESS',
  CREATE_ACCOUNT_MEMBER_FAILURE: 'CREATE_ACCOUNT_MEMBER_FAILURE',
  EDIT_ACCOUNT_MEMBER_REQUEST: 'EDIT_ACCOUNT_MEMBER_REQUEST',
  EDIT_ACCOUNT_MEMBER_SUCCESS: 'EDIT_ACCOUNT_MEMBER_SUCCESS',
  EDIT_ACCOUNT_MEMBER_FAILURE: 'EDIT_ACCOUNT_MEMBER_FAILURE',
  DELETE_ACCOUNT_MEMBER_REQUEST: 'DELETE_ACCOUNT_MEMBER_REQUEST',
  DELETE_ACCOUNT_MEMBER_SUCCESS: 'DELETE_ACCOUNT_MEMBER_SUCCESS',
  DELETE_ACCOUNT_MEMBER_FAILURE: 'DELETE_ACCOUNT_MEMBER_FAILURE',
};

export { accountMembersTypes };