const accountsTypes = {
  GET_ACCOUNTS_REQUEST: 'GET_ACCOUNTS_REQUEST',
  GET_ACCOUNTS_SUCCESS: 'GET_ACCOUNTS_SUCCESS',
  GET_ACCOUNTS_FAILURE: 'GET_ACCOUNTS_FAILURE',
  CREATE_ACCOUNTS_REQUEST: 'CREATE_ACCOUNTS_REQUEST',
  CREATE_ACCOUNTS_SUCCESS: 'CREATE_ACCOUNTS_SUCCESS',
  CREATE_ACCOUNTS_FAILURE: 'CREATE_ACCOUNTS_FAILURE',
  EDIT_ACCOUNTS_REQUEST: 'EDIT_ACCOUNTS_REQUEST',
  EDIT_ACCOUNTS_SUCCESS: 'EDIT_ACCOUNTS_SUCCESS',
  EDIT_ACCOUNTS_FAILURE: 'EDIT_ACCOUNTS_FAILURE',
  DELETE_ACCOUNTS_REQUEST: 'DELETE_ACCOUNTS_REQUEST',
  DELETE_ACCOUNTS_SUCCESS: 'DELETE_ACCOUNTS_SUCCESS',
  DELETE_ACCOUNTS_FAILURE: 'DELETE_ACCOUNTS_FAILURE',
};

export { accountsTypes };