const bankAccountsTypes = {
  GET_BANK_ACCOUNTS_REQUEST: 'GET_BANK_ACCOUNTS_REQUEST',
  GET_BANK_ACCOUNTS_SUCCESS: 'GET_BANK_ACCOUNTS_SUCCESS',
  GET_BANK_ACCOUNTS_FAILURE: 'GET_BANK_ACCOUNTS_FAILURE',
  CREATE_BANK_ACCOUNT_REQUEST: 'CREATE_BANK_ACCOUNT_REQUEST',
  CREATE_BANK_ACCOUNT_SUCCESS: 'CREATE_BANK_ACCOUNT_SUCCESS',
  CREATE_BANK_ACCOUNT_FAILURE: 'CREATE_BANK_ACCOUNT_FAILURE',
  EDIT_BANK_ACCOUNT_REQUEST: 'EDIT_BANK_ACCOUNT_REQUEST',
  EDIT_BANK_ACCOUNT_SUCCESS: 'EDIT_BANK_ACCOUNT_SUCCESS',
  EDIT_BANK_ACCOUNT_FAILURE: 'EDIT_BANK_ACCOUNT_FAILURE',
  DELETE_BANK_ACCOUNT_REQUEST: 'DELETE_BANK_ACCOUNT_REQUEST',
  DELETE_BANK_ACCOUNT_SUCCESS: 'DELETE_BANK_ACCOUNT_SUCCESS',
  DELETE_BANK_ACCOUNT_FAILURE: 'DELETE_BANK_ACCOUNT_FAILURE',
};

export { bankAccountsTypes };