const expensesTypes = {
  GET_EXPENSES_REQUEST: 'GET_EXPENSES_REQUEST',
  GET_EXPENSES_SUCCESS: 'GET_EXPENSES_SUCCESS',
  GET_EXPENSES_FAILURE: 'GET_EXPENSES_FAILURE',
  CREATE_EXPENSE_REQUEST: 'CREATE_EXPENSE_REQUEST',
  CREATE_EXPENSE_SUCCESS: 'CREATE_EXPENSE_SUCCESS',
  CREATE_EXPENSE_FAILURE: 'CREATE_EXPENSE_FAILURE',
  EDIT_EXPENSE_REQUEST: 'EDIT_EXPENSE_REQUEST',
  EDIT_EXPENSE_SUCCESS: 'EDIT_EXPENSE_SUCCESS',
  EDIT_EXPENSE_FAILURE: 'EDIT_EXPENSE_FAILURE',
  DELETE_EXPENSE_REQUEST: 'DELETE_EXPENSE_REQUEST',
  DELETE_EXPENSE_SUCCESS: 'DELETE_EXPENSE_SUCCESS',
  DELETE_EXPENSE_FAILURE: 'DELETE_EXPENSE_FAILURE',
  CLEAR_EXPENSES: 'CLEAR_EXPENSES'
};

export { expensesTypes };