const incomesTypes = {
  GET_INCOMES_REQUEST: 'GET_INCOMES_REQUEST',
  GET_INCOMES_SUCCESS: 'GET_INCOMES_SUCCESS',
  GET_INCOMES_FAILURE: 'GET_INCOMES_FAILURE',
  CREATE_INCOME_REQUEST: 'CREATE_INCOME_REQUEST',
  CREATE_INCOME_SUCCESS: 'CREATE_INCOME_SUCCESS',
  CREATE_INCOME_FAILURE: 'CREATE_INCOME_FAILURE',
  EDIT_INCOME_REQUEST: 'EDIT_INCOME_REQUEST',
  EDIT_INCOME_SUCCESS: 'EDIT_INCOME_SUCCESS',
  EDIT_INCOME_FAILURE: 'EDIT_INCOME_FAILURE',
  DELETE_INCOME_REQUEST: 'DELETE_INCOME_REQUEST',
  DELETE_INCOME_SUCCESS: 'DELETE_INCOME_SUCCESS',
  DELETE_INCOME_FAILURE: 'DELETE_INCOME_FAILURE',
};

export { incomesTypes };