const userTypes = {
  LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
  EDIT_USER_REQUEST: 'EDIT_USER_REQUEST',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',
  EDIT_USER_PASSWORD_REQUEST: 'EDIT_USER_PASSWORD_REQUEST',
  EDIT_USER_PASSWORD_SUCCESS: 'EDIT_USER_PASSWORD_SUCCESS',
  EDIT_USER_PASSWORD_FAILURE: 'EDIT_USER_PASSWORD_FAILURE',
};

export { userTypes };
